[project]
name = "hot-reloaded"
version = "0.0.0"
description = "Dev tooling for formatting and linting GDScript"
readme = "README.md"
requires-python = ">=3.11"

[dependency-groups]

dev = [
  "gdtoolkit==4.3.0",
  "setuptools>=70.0.0",
]

[tool.uv]
default-groups = ["dev"]

